### ISSUE TITLE
Rick 1st issue with edit adding some words

### ISSUE THREAD

**Issue by ricka** [appirio-digital/lissa-test-1#1]
And additional context like acceptance criteria

**Comment by ricka** [comment]
My first comment here

**Comment by lissa-robinson** [comment]
My first Zenhub comment

**Comment by ricka** [comment]
New comment goes here with status update

**Comment by ricka** [comment]
One more comment here

**Comment by lissa-robinson** [comment]
➤ Lissa Robinson commented:

testing commenting with asana
